#!/bin/zsh
# description: compile and run a c++ file quickly
if [ "$1" = "-b" ]; then
    src="$2"
    file="${src%.cpp}"
    g++ -o "$file" "$src" && ./"$file"
else
    src="$1"
    file="${src%.cpp}"
    g++ -o "$file" "$src" && ./"$file" && rm ./"$file"
fi
