#!/bin/zsh
# description: compile and run a C file quickly

if [ "$1" = "-b" ]; then
    file="$2"
    gcc -o "$file" "$file.c" && ./"$file"
else
    file="$1"
    gcc -o "$file" "$file.c" && ./"$file" && rm ./"$file"
fi
